version: "3.8"
services:
  backend:
    container_name: rails_auth
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - ".:/app"
    networks:
      - trandung
networks:
  trandung:
